
package MenuPrincipal;

import AppPackage.AnimationClass;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author JDCR03
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVendedor = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cejillavendedor.png"))); // NOI18N
        btnVendedor.setBorder(null);
        btnVendedor.setBorderPainted(false);
        btnVendedor.setContentAreaFilled(false);
        btnVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVendedorMouseClicked(evt);
            }
        });
        getContentPane().add(btnVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 100, 270, 85));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/sejillaCliente.png"))); // NOI18N
        btnCliente.setBorder(null);
        btnCliente.setBorderPainted(false);
        btnCliente.setContentAreaFilled(false);
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteMouseClicked(evt);
            }
        });
        getContentPane().add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 200, 270, 90));

        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/SejillaProducto.png"))); // NOI18N
        btnProducto.setBorder(null);
        btnProducto.setBorderPainted(false);
        btnProducto.setContentAreaFilled(false);
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductoMouseClicked(evt);
            }
        });
        getContentPane().add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 300, 270, 90));

        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menun.png"))); // NOI18N
        btnMenu1.setBorder(null);
        btnMenu1.setBorderPainted(false);
        btnMenu1.setContentAreaFilled(false);
        btnMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenu1MouseClicked(evt);
            }
        });
        getContentPane().add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 70));

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/VENTAS1.png"))); // NOI18N
        btnVentas.setBorder(null);
        btnVentas.setBorderPainted(false);
        btnVentas.setContentAreaFilled(false);
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 280, 80));

        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/CONSULTAS1.png"))); // NOI18N
        btnConsultas.setBorder(null);
        btnConsultas.setBorderPainted(false);
        btnConsultas.setContentAreaFilled(false);
        btnConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultasMouseClicked(evt);
            }
        });
        getContentPane().add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, 280, 90));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/comeback.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 390, 50, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salir.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, -1, 60));

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/portada2.jpg"))); // NOI18N
        labelfondo.setToolTipText("");
        getContentPane().add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseClicked
        
        AnimationClass ac= new AnimationClass();
        ac.jButtonXRight(-270, 0, 20, 5, btnVendedor);
        ac.jButtonXRight(-270, 0, 20, 5, btnCliente);
        ac.jButtonXRight(-270, 0, 20, 5, btnProducto);
        ac.jButtonXRight(-50, 50, 35, 5, btnBack);
        AnimationClass vc= new AnimationClass();
        vc.jButtonXLeft(1000, 720, 20, 5, btnVentas);
        vc.jButtonXLeft(1000, 720, 20, 5, btnConsultas);
        
    }//GEN-LAST:event_btnMenu1MouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        //RSAnimation.setMoverIzquierda(0, -270, 20, 5, jPanel1);
       AnimationClass at= new AnimationClass();
       at.jButtonXLeft(0, -270, 20, 5, btnVendedor);
       at.jButtonXLeft(0, -270, 20, 5, btnCliente);
       at.jButtonXLeft(0, -270, 20, 5, btnProducto);
       at.jButtonXLeft(50, -50, 20, 5, btnBack);
       AnimationClass vci= new AnimationClass();
       vci.jButtonXRight(720, 1000, 20, 5, btnVentas);
       vci.jButtonXRight(720, 1000, 20, 5, btnConsultas);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendedorMouseClicked
         new BaseDatosVendedores(this, true).setVisible(true);
    }//GEN-LAST:event_btnVendedorMouseClicked

    private void btnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseClicked
        new BaseDatosClientes(this, true).setVisible(true);
    }//GEN-LAST:event_btnClienteMouseClicked

    private void btnProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMouseClicked
        new BaseDatosProductos(this, true).setVisible(true);
    }//GEN-LAST:event_btnProductoMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int resul = JOptionPane.showConfirmDialog(null, "Desea cerrar el sistema?", "EXIT", dialogButton);
            if (resul == 0) {
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasMouseClicked
      new MenuConsultas(this, true).setVisible(true);
    }//GEN-LAST:event_btnConsultasMouseClicked

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
        new Ventas(this, true).setVisible(true);
    }//GEN-LAST:event_btnVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel labelfondo;
    // End of variables declaration//GEN-END:variables
}
